"use client";
import { getProject } from "@/lib/mock-data";
import { ImportedJiraIssue, ProjectImportBundle, ProjectOverride, ProjectRecord } from "@/lib/types";
const STORAGE_PREFIX = "releasegovernance.projectOverride.";
const dedupe = <T extends { id?: string }>(items: T[]) => { const seen = new Set<string>(); return items.filter((item) => { const id = item.id ?? JSON.stringify(item); if (seen.has(id)) return false; seen.add(id); return true; }); };
const dedupeJira = (items: ImportedJiraIssue[]) => { const seen = new Set<string>(); return items.filter((item) => { const id = item.key || item.id; if (seen.has(id)) return false; seen.add(id); return true; }); };
export function readProjectOverride(projectId: string): ProjectOverride { if (typeof window === "undefined") return {}; try { const raw = localStorage.getItem(`${STORAGE_PREFIX}${projectId}`); return raw ? JSON.parse(raw) : {}; } catch { return {}; } }
export function writeProjectOverride(projectId: string, override: ProjectOverride) { if (typeof window === "undefined") return; localStorage.setItem(`${STORAGE_PREFIX}${projectId}`, JSON.stringify(override)); }
export function applyImportBundle(projectId: string, bundle: ProjectImportBundle) { const current = readProjectOverride(projectId); writeProjectOverride(projectId, { releases: dedupe([...(current.releases ?? []), ...bundle.releases]), capabilities: dedupe([...(current.capabilities ?? []), ...bundle.capabilities]), integrations: dedupe([...(current.integrations ?? []), ...bundle.integrations]), importedJiraIssues: dedupeJira([...(current.importedJiraIssues ?? []), ...bundle.importedJiraIssues]) }); }
export function mergeProjectWithOverrides(projectId: string): ProjectRecord | undefined { const base = getProject(projectId); if (!base) return undefined; const current = readProjectOverride(projectId); return { ...base, releases: dedupe([...(base.releases ?? []), ...(current.releases ?? [])]), capabilities: dedupe([...(base.capabilities ?? []), ...(current.capabilities ?? [])]), integrations: dedupe([...(base.integrations ?? []), ...(current.integrations ?? [])]), importedJiraIssues: dedupeJira([...(base.importedJiraIssues ?? []), ...(current.importedJiraIssues ?? [])]) }; }
